window.esdocSearchIndex = [
  [
    "origin_project/scripts/framework/component.js~component",
    "class/scripts/framework/Component.js~Component.html",
    "<span>Component</span> <span class=\"search-result-import-path\">origin_project/scripts/framework/Component.js</span>",
    "class"
  ],
  [
    "origin_project/scripts/framework/eventdispatcher.js~eventdispatcher",
    "class/scripts/framework/EventDispatcher.js~EventDispatcher.html",
    "<span>EventDispatcher</span> <span class=\"search-result-import-path\">origin_project/scripts/framework/EventDispatcher.js</span>",
    "class"
  ],
  [
    "origin_project/scripts/framework/store.js~store",
    "class/scripts/framework/Store.js~Store.html",
    "<span>Store</span> <span class=\"search-result-import-path\">origin_project/scripts/framework/Store.js</span>",
    "class"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "scripts/app/app.js",
    "file/scripts/app/app.js.html",
    "scripts/app/app.js",
    "file"
  ],
  [
    "scripts/app/stores/basestore.js",
    "file/scripts/app/stores/BaseStore.js.html",
    "scripts/app/stores/BaseStore.js",
    "file"
  ],
  [
    "scripts/app/stores/propertystore.js",
    "file/scripts/app/stores/PropertyStore.js.html",
    "scripts/app/stores/PropertyStore.js",
    "file"
  ],
  [
    "scripts/framework/appdispatcher.js",
    "file/scripts/framework/AppDispatcher.js.html",
    "scripts/framework/AppDispatcher.js",
    "file"
  ],
  [
    "scripts/framework/component.js",
    "file/scripts/framework/Component.js.html",
    "scripts/framework/Component.js",
    "file"
  ],
  [
    "scripts/framework/component.js~component#constructor",
    "class/scripts/framework/Component.js~Component.html#instance-constructor-constructor",
    "scripts/framework/Component.js~Component#constructor",
    "method"
  ],
  [
    "scripts/framework/component.js~component#el",
    "class/scripts/framework/Component.js~Component.html#instance-member-el",
    "scripts/framework/Component.js~Component#el",
    "member"
  ],
  [
    "scripts/framework/component.js~component#on",
    "class/scripts/framework/Component.js~Component.html#instance-method-on",
    "scripts/framework/Component.js~Component#on",
    "method"
  ],
  [
    "scripts/framework/component.js~component#props",
    "class/scripts/framework/Component.js~Component.html#instance-member-props",
    "scripts/framework/Component.js~Component#props",
    "member"
  ],
  [
    "scripts/framework/component.js~component#setstate",
    "class/scripts/framework/Component.js~Component.html#instance-method-setState",
    "scripts/framework/Component.js~Component#setState",
    "method"
  ],
  [
    "scripts/framework/component.js~component#state",
    "class/scripts/framework/Component.js~Component.html#instance-member-state",
    "scripts/framework/Component.js~Component#state",
    "member"
  ],
  [
    "scripts/framework/eventdispatcher.js",
    "file/scripts/framework/EventDispatcher.js.html",
    "scripts/framework/EventDispatcher.js",
    "file"
  ],
  [
    "scripts/framework/eventdispatcher.js~eventdispatcher#dispatch",
    "class/scripts/framework/EventDispatcher.js~EventDispatcher.html#instance-method-dispatch",
    "scripts/framework/EventDispatcher.js~EventDispatcher#dispatch",
    "method"
  ],
  [
    "scripts/framework/eventdispatcher.js~eventdispatcher#off",
    "class/scripts/framework/EventDispatcher.js~EventDispatcher.html#instance-method-off",
    "scripts/framework/EventDispatcher.js~EventDispatcher#off",
    "method"
  ],
  [
    "scripts/framework/eventdispatcher.js~eventdispatcher#on",
    "class/scripts/framework/EventDispatcher.js~EventDispatcher.html#instance-method-on",
    "scripts/framework/EventDispatcher.js~EventDispatcher#on",
    "method"
  ],
  [
    "scripts/framework/store.js",
    "file/scripts/framework/Store.js.html",
    "scripts/framework/Store.js",
    "file"
  ],
  [
    "scripts/framework/store.js~store#addchangelistener",
    "class/scripts/framework/Store.js~Store.html#instance-method-addChangeListener",
    "scripts/framework/Store.js~Store#addChangeListener",
    "method"
  ],
  [
    "scripts/framework/store.js~store#constructor",
    "class/scripts/framework/Store.js~Store.html#instance-constructor-constructor",
    "scripts/framework/Store.js~Store#constructor",
    "method"
  ],
  [
    "scripts/framework/store.js~store#dispatchchange",
    "class/scripts/framework/Store.js~Store.html#instance-method-dispatchChange",
    "scripts/framework/Store.js~Store#dispatchChange",
    "method"
  ],
  [
    "scripts/framework/store.js~store#register",
    "class/scripts/framework/Store.js~Store.html#instance-method-register",
    "scripts/framework/Store.js~Store#register",
    "method"
  ],
  [
    "scripts/framework/store.js~store#removechangelistener",
    "class/scripts/framework/Store.js~Store.html#instance-method-removeChangeListener",
    "scripts/framework/Store.js~Store#removeChangeListener",
    "method"
  ],
  [
    "scripts/libs/touchable.js",
    "file/scripts/libs/touchable.js.html",
    "scripts/libs/touchable.js",
    "file"
  ]
]